# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AkImageMatrix' do

  pod 'SDWebImage'
  #支持webp
  pod 'SDWebImage/WebP'
  #支持gif
  pod 'SDWebImage/GIF'
end
